# what rules to check against
select = ["F", "E", "W", "I", "NPY", "S", "B", "BLE", "A", "COM", "C4", "T10", "RET", "ARG", "PL", "TRY", "RUF"]


# rules to ignore
ignore = ["E501", "RET505", "E731", "B905", "PLR0913", "ARG001", "B028"]

# Rule explanations:
# E501: line too long
# RET505:  Unnecessary `{branch}` after `return` statement
# E731: do not assign a lambda expression, use a def
# B905: Use of zip without strict parameter
# PLR0913: to many arguments
# ARG001: unused argument
# B028: use of warning without stack level declared


# exclude some directories
exclude = ['tests', 'docs', '.github']

[per-file-ignores]

[mccabe]
max-complexity = 10