from tests.test_fixtures import single_location_scenario_variability, single_location_lp_variability_cost, single_location_lp_variability_profit
from src.energiapy.model.solve import solve
from src.energiapy.model.formulate import formulate


def test_results_single_location_lp_variability_cost(single_location_scenario_variability, single_location_lp_variability_cost):
    results = solve(scenario=single_location_scenario_variability,
                    instance=single_location_lp_variability_cost, solver='gurobi', name='LP')

    assert (results.output == {'termination': 'optimal',
                               'LB': 47423.33333333333,
                               'UB': 47423.33333333333,
                               'n_cons': 155,
                               'n_vars': 138,
                               'n_binvars': 0,
                               'n_intvars': 0,
                               'n_convars': 138,
                               'n_nonzero': 350,
                               'P': {('location', 'process_certain_capacity', 0, 0): 25.0,
                                     ('location', 'process_certain_capacity', 0, 1): 25.0,
                                     ('location', 'process_certain_capacity', 0, 2): 25.0,
                                     ('location', 'process_certain_capacity', 0, 3): 25.0,
                                     ('location', 'process_deterministic_capacity', 0, 0): 41.666666666666664,
                                     ('location', 'process_deterministic_capacity', 0, 1): 20.833333333333332,
                                     ('location', 'process_deterministic_capacity', 0, 2): 33.333333333333336,
                                     ('location', 'process_deterministic_capacity', 0, 3): 10.416666666666666,
                                     ('location', 'process_storage', 0, 0): 16.666666666666668,
                                     ('location', 'process_storage', 0, 1): 0.0,
                                     ('location', 'process_storage', 0, 2): 8.333333333333334,
                                     ('location', 'process_storage', 0, 3): 0.0,
                                     ('location', 'process_storage_discharge', 0, 0): 0.0,
                                     ('location', 'process_storage_discharge', 0, 1): 16.666666666666668,
                                     ('location', 'process_storage_discharge', 0, 2): 0.0,
                                     ('location', 'process_storage_discharge', 0, 3): 8.333333333333334},
                               'B': {('location', 'resource_certain_availability', 0, 0): 83.33333333333333,
                                     ('location', 'resource_certain_availability', 0, 1): 41.666666666666664,
                                     ('location', 'resource_certain_availability', 0, 2): 66.66666666666667,
                                     ('location', 'resource_certain_availability', 0, 3): 20.833333333333332,
                                     ('location', 'resource_deterministic_availability', 0, 0): 62.5,
                                     ('location', 'resource_deterministic_availability', 0, 1): 62.5,
                                     ('location', 'resource_deterministic_availability', 0, 2): 62.5,
                                     ('location', 'resource_deterministic_availability', 0, 3): 62.5,
                                     ('location', 'resource_deterministic_price', 0, 0): 15.625,
                                     ('location', 'resource_deterministic_price', 0, 1): 62.5,
                                     ('location', 'resource_deterministic_price', 0, 2): 31.25,
                                     ('location', 'resource_deterministic_price', 0, 3): 46.875},
                               'C': {('location', 'resource_certain_availability', 0, 0): 41.666666666666664,
                                     ('location', 'resource_certain_availability', 0, 1): 20.833333333333332,
                                     ('location', 'resource_certain_availability', 0, 2): 33.333333333333336,
                                     ('location', 'resource_certain_availability', 0, 3): 10.416666666666666,
                                     ('location', 'resource_deterministic_availability', 0, 0): 12.5,
                                     ('location', 'resource_deterministic_availability', 0, 1): 12.5,
                                     ('location', 'resource_deterministic_availability', 0, 2): 12.5,
                                     ('location', 'resource_deterministic_availability', 0, 3): 12.5,
                                     ('location', 'resource_deterministic_price', 0, 0): 6.25,
                                     ('location', 'resource_deterministic_price', 0, 1): 6.25,
                                     ('location', 'resource_deterministic_price', 0, 2): 6.25,
                                     ('location', 'resource_deterministic_price', 0, 3): 6.25},
                               'S': {('location', 'resource_deterministic_demand', 0, 0): 12.5,
                                     ('location', 'resource_deterministic_demand', 0, 1): 25.0,
                                     ('location', 'resource_deterministic_demand', 0, 2): 12.5,
                                     ('location', 'resource_deterministic_demand', 0, 3): 6.25,
                                     ('location', 'resource_deterministic_revenue', 0, 0): 25.0,
                                     ('location', 'resource_deterministic_revenue', 0, 1): 25.0,
                                     ('location', 'resource_deterministic_revenue', 0, 2): 25.0,
                                     ('location', 'resource_deterministic_revenue', 0, 3): 25.0},
                               'R': {('location', 'resource_deterministic_demand', 0, 0): None,
                                     ('location', 'resource_deterministic_demand', 0, 1): None,
                                     ('location', 'resource_deterministic_demand', 0, 2): None,
                                     ('location', 'resource_deterministic_demand', 0, 3): None,
                                     ('location', 'resource_deterministic_revenue', 0, 0): None,
                                     ('location', 'resource_deterministic_revenue', 0, 1): None,
                                     ('location', 'resource_deterministic_revenue', 0, 2): None,
                                     ('location', 'resource_deterministic_revenue', 0, 3): None},
                               'Inv': {('location',
                                        'process_storage_resource_deterministic_demand_stored',
                                        0,
                                        0): 16.666666666666668,
                                       ('location',
                                        'process_storage_resource_deterministic_demand_stored',
                                        0,
                                        1): 0.0,
                                       ('location',
                                        'process_storage_resource_deterministic_demand_stored',
                                        0,
                                        2): 8.333333333333334,
                                       ('location',
                                        'process_storage_resource_deterministic_demand_stored',
                                        0,
                                        3): 0.0},
                               'P_m': {('location', 'process_storage', 0, 0, 0): 16.666666666666668,
                                       ('location', 'process_storage', 0, 0, 1): 0.0,
                                       ('location', 'process_storage', 0, 0, 2): 8.333333333333334,
                                       ('location', 'process_storage', 0, 0, 3): 0.0,
                                       ('location', 'process_certain_capacity', 0, 0, 0): 25.0,
                                       ('location', 'process_certain_capacity', 0, 0, 1): 25.0,
                                       ('location', 'process_certain_capacity', 0, 0, 2): 25.0,
                                       ('location', 'process_certain_capacity', 0, 0, 3): 25.0,
                                       ('location', 'process_storage_discharge', 0, 0, 0): 0.0,
                                       ('location', 'process_storage_discharge', 0, 0, 1): 16.666666666666668,
                                       ('location', 'process_storage_discharge', 0, 0, 2): 0.0,
                                       ('location', 'process_storage_discharge', 0, 0, 3): 8.333333333333334,
                                       ('location', 'process_deterministic_capacity', 0, 0, 0): 41.666666666666664,
                                       ('location', 'process_deterministic_capacity', 0, 0, 1): 20.833333333333332,
                                       ('location', 'process_deterministic_capacity', 0, 0, 2): 33.333333333333336,
                                       ('location', 'process_deterministic_capacity', 0, 0, 3): 10.416666666666666},
                               'P_material_m': {},
                               'Cap_P': {('location', 'process_certain_capacity', 0): 25.0,
                                         ('location', 'process_deterministic_capacity', 0): 41.666666666666664,
                                         ('location', 'process_storage', 0): 16.666666666666668,
                                         ('location', 'process_storage_discharge', 0): 50.0},
                               'Cap_S': {('location',
                                          'process_storage_resource_deterministic_demand_stored',
                                          0): 25.0},
                               'P_location': {('location', 'process_certain_capacity', 0): 100.0,
                                              ('location', 'process_deterministic_capacity', 0): 106.25,
                                              ('location', 'process_storage', 0): 25.0,
                                              ('location', 'process_storage_discharge', 0): 25.0},
                               'P_location_material_m': {},
                               'S_location': {('location', 'resource_deterministic_demand', 0): 56.25,
                                              ('location', 'resource_deterministic_revenue', 0): 100.0},
                               'R_location': {('location', 'resource_deterministic_demand', 0): None,
                                              ('location', 'resource_deterministic_revenue', 0): None},
                               'C_location': {('location',
                                               'resource_certain_availability',
                                               0): 106.25000000000001,
                                              ('location', 'resource_deterministic_availability', 0): 50.0,
                                              ('location', 'resource_deterministic_price', 0): 25.0},
                               'B_location': {('location',
                                               'resource_certain_availability',
                                               0): 212.50000000000003,
                                              ('location', 'resource_deterministic_availability', 0): 250.0,
                                              ('location', 'resource_deterministic_price', 0): 156.25},
                               'P_network': {('process_certain_capacity', 0): 100.0,
                                             ('process_deterministic_capacity', 0): 106.25,
                                             ('process_storage', 0): 25.0,
                                             ('process_storage_discharge', 0): 25.0},
                               'S_network': {('resource_deterministic_demand', 0): 56.25,
                                             ('resource_deterministic_revenue', 0): 100.0},
                               'R_network': {('resource_deterministic_demand', 0): None,
                                             ('resource_deterministic_revenue', 0): None},
                               'C_network': {('resource_certain_availability', 0): 106.25000000000001,
                                             ('resource_deterministic_availability', 0): 50.0,
                                             ('resource_deterministic_price', 0): 25.0},
                               'B_network': {('resource_certain_availability', 0): 212.50000000000003,
                                             ('resource_deterministic_availability', 0): 250.0,
                                             ('resource_deterministic_price', 0): 156.25},
                               'Fopex_process': {('location', 'process_certain_capacity', 0): 250.0,
                                                 ('location', 'process_deterministic_capacity', 0): 416.66666666666663,
                                                 ('location', 'process_storage', 0): 83.33333333333334,
                                                 ('location', 'process_storage_discharge', 0): 0.0},
                               'Vopex_process': {('location', 'process_certain_capacity', 0): 100.0,
                                                 ('location', 'process_deterministic_capacity', 0): 106.25,
                                                 ('location', 'process_storage', 0): 12.5,
                                                 ('location', 'process_storage_discharge', 0): 0.0},
                               'Capex_process': {('location', 'process_certain_capacity', 0): 2500.0,
                                                 ('location', 'process_deterministic_capacity', 0): 41666.666666666664,
                                                 ('location', 'process_storage', 0): 1666.6666666666667,
                                                 ('location', 'process_storage_discharge', 0): 0.0},
                               'Incidental_process': {('location', 'process_certain_capacity', 0): 0.0,
                                                      ('location', 'process_deterministic_capacity', 0): 0.0,
                                                      ('location', 'process_storage', 0): 0.0,
                                                      ('location', 'process_storage_discharge', 0): 0.0},
                               'Fopex_location': {('location', 0): 750.0},
                               'Vopex_location': {('location', 0): 218.75},
                               'Capex_location': {('location', 0): 45833.33333333333},
                               'Incidental_location': {('location', 0): 0.0},
                               'Fopex_network': {0: 750.0},
                               'Vopex_network': {0: 218.75},
                               'Capex_network': {0: 45833.33333333333},
                               'Incidental_network': {0: 0.0},
                               'Inv_network': {('location',
                                                'process_storage_resource_deterministic_demand_stored',
                                                0): 25.0},
                               'Cost_network': {None: 47423.33333333333},
                               'Inv_cost': {('location',
                                             'process_storage_resource_deterministic_demand_stored',
                                             0): 2.5},
                               'Inv_cost_location': {('location', 0): 2.5},
                               'Inv_cost_network': {0: 2.5},
                               'objective': 47423.33333333333})


def test_results_single_location_lp_variability_profit(single_location_scenario_variability, single_location_lp_variability_profit):
    results = solve(scenario=single_location_scenario_variability,
                    instance=single_location_lp_variability_profit, solver='gurobi', name='LP')

    assert (results.output == {'termination': 'optimal',
                               'LB': 15977.8125,
                               'UB': 15977.8125,
                               'n_cons': 159,
                               'n_vars': 138,
                               'n_binvars': 0,
                               'n_intvars': 0,
                               'n_convars': 138,
                               'n_nonzero': 368,
                               'P': {('location', 'process_certain_capacity', 0, 0): 0.0,
                                     ('location', 'process_certain_capacity', 0, 1): 75.0,
                                     ('location', 'process_certain_capacity', 0, 2): 0.0,
                                     ('location', 'process_certain_capacity', 0, 3): 62.5,
                                     ('location', 'process_deterministic_capacity', 0, 0): 25.0,
                                     ('location', 'process_deterministic_capacity', 0, 1): 12.5,
                                     ('location', 'process_deterministic_capacity', 0, 2): 25.0,
                                     ('location', 'process_deterministic_capacity', 0, 3): 6.25,
                                     ('location', 'process_storage', 0, 0): 25.0,
                                     ('location', 'process_storage', 0, 1): 0.0,
                                     ('location', 'process_storage', 0, 2): 25.0,
                                     ('location', 'process_storage', 0, 3): 0.0,
                                     ('location', 'process_storage_discharge', 0, 0): 0.0,
                                     ('location', 'process_storage_discharge', 0, 1): 25.0,
                                     ('location', 'process_storage_discharge', 0, 2): 0.0,
                                     ('location', 'process_storage_discharge', 0, 3): 25.0},
                               'B': {('location', 'resource_certain_availability', 0, 0): 50.0,
                                     ('location', 'resource_certain_availability', 0, 1): 25.0,
                                     ('location', 'resource_certain_availability', 0, 2): 50.0,
                                     ('location', 'resource_certain_availability', 0, 3): 12.5,
                                     ('location', 'resource_deterministic_availability', 0, 0): 0.0,
                                     ('location', 'resource_deterministic_availability', 0, 1): 187.5,
                                     ('location', 'resource_deterministic_availability', 0, 2): 0.0,
                                     ('location', 'resource_deterministic_availability', 0, 3): 156.25,
                                     ('location', 'resource_deterministic_price', 0, 0): 0.0,
                                     ('location', 'resource_deterministic_price', 0, 1): 187.5,
                                     ('location', 'resource_deterministic_price', 0, 2): 0.0,
                                     ('location', 'resource_deterministic_price', 0, 3): 117.1875},
                               'C': {('location', 'resource_certain_availability', 0, 0): 25.0,
                                     ('location', 'resource_certain_availability', 0, 1): 12.5,
                                     ('location', 'resource_certain_availability', 0, 2): 25.0,
                                     ('location', 'resource_certain_availability', 0, 3): 6.25,
                                     ('location', 'resource_deterministic_availability', 0, 0): 0.0,
                                     ('location', 'resource_deterministic_availability', 0, 1): 37.5,
                                     ('location', 'resource_deterministic_availability', 0, 2): 0.0,
                                     ('location', 'resource_deterministic_availability', 0, 3): 31.25,
                                     ('location', 'resource_deterministic_price', 0, 0): 0.0,
                                     ('location', 'resource_deterministic_price', 0, 1): 18.75,
                                     ('location', 'resource_deterministic_price', 0, 2): 0.0,
                                     ('location', 'resource_deterministic_price', 0, 3): 15.625},
                               'S': {('location', 'resource_deterministic_demand', 0, 0): 0.0,
                                     ('location', 'resource_deterministic_demand', 0, 1): 0.0,
                                     ('location', 'resource_deterministic_demand', 0, 2): 0.0,
                                     ('location', 'resource_deterministic_demand', 0, 3): 0.0,
                                     ('location', 'resource_deterministic_revenue', 0, 0): 0.0,
                                     ('location', 'resource_deterministic_revenue', 0, 1): 75.0,
                                     ('location', 'resource_deterministic_revenue', 0, 2): 0.0,
                                     ('location', 'resource_deterministic_revenue', 0, 3): 62.5},
                               'R': {('location', 'resource_deterministic_demand', 0, 0): 0.0,
                                     ('location', 'resource_deterministic_demand', 0, 1): 0.0,
                                     ('location', 'resource_deterministic_demand', 0, 2): 0.0,
                                     ('location', 'resource_deterministic_demand', 0, 3): 0.0,
                                     ('location', 'resource_deterministic_revenue', 0, 0): 0.0,
                                     ('location', 'resource_deterministic_revenue', 0, 1): 37500.0,
                                     ('location', 'resource_deterministic_revenue', 0, 2): 0.0,
                                     ('location', 'resource_deterministic_revenue', 0, 3): 15625.0},
                               'Inv': {('location',
                                        'process_storage_resource_deterministic_demand_stored',
                                        0,
                                        0): 25.0,
                                       ('location',
                                        'process_storage_resource_deterministic_demand_stored',
                                        0,
                                        1): 0.0,
                                       ('location',
                                        'process_storage_resource_deterministic_demand_stored',
                                        0,
                                        2): 25.0,
                                       ('location',
                                        'process_storage_resource_deterministic_demand_stored',
                                        0,
                                        3): 0.0},
                               'P_m': {('location', 'process_storage', 0, 0, 0): 25.0,
                                       ('location', 'process_storage', 0, 0, 1): 0.0,
                                       ('location', 'process_storage', 0, 0, 2): 25.0,
                                       ('location', 'process_storage', 0, 0, 3): 0.0,
                                       ('location', 'process_certain_capacity', 0, 0, 0): 0.0,
                                       ('location', 'process_certain_capacity', 0, 0, 1): 75.0,
                                       ('location', 'process_certain_capacity', 0, 0, 2): 0.0,
                                       ('location', 'process_certain_capacity', 0, 0, 3): 62.5,
                                       ('location', 'process_storage_discharge', 0, 0, 0): 0.0,
                                       ('location', 'process_storage_discharge', 0, 0, 1): 25.0,
                                       ('location', 'process_storage_discharge', 0, 0, 2): 0.0,
                                       ('location', 'process_storage_discharge', 0, 0, 3): 25.0,
                                       ('location', 'process_deterministic_capacity', 0, 0, 0): 25.0,
                                       ('location', 'process_deterministic_capacity', 0, 0, 1): 12.5,
                                       ('location', 'process_deterministic_capacity', 0, 0, 2): 25.0,
                                       ('location', 'process_deterministic_capacity', 0, 0, 3): 6.25},
                               'P_material_m': {},
                               'Cap_P': {('location', 'process_certain_capacity', 0): 75.0,
                                         ('location', 'process_deterministic_capacity', 0): 25.0,
                                         ('location', 'process_storage', 0): 25.0,
                                         ('location', 'process_storage_discharge', 0): 50.0},
                               'Cap_S': {('location',
                                          'process_storage_resource_deterministic_demand_stored',
                                          0): 25.0},
                               'P_location': {('location', 'process_certain_capacity', 0): 137.5,
                                              ('location', 'process_deterministic_capacity', 0): 68.75,
                                              ('location', 'process_storage', 0): 50.0,
                                              ('location', 'process_storage_discharge', 0): 50.0},
                               'P_location_material_m': {},
                               'S_location': {('location', 'resource_deterministic_demand', 0): 0.0,
                                              ('location', 'resource_deterministic_revenue', 0): 137.5},
                               'R_location': {('location', 'resource_deterministic_demand', 0): 0.0,
                                              ('location', 'resource_deterministic_revenue', 0): 53125.0},
                               'C_location': {('location', 'resource_certain_availability', 0): 68.75,
                                              ('location', 'resource_deterministic_availability', 0): 68.75,
                                              ('location', 'resource_deterministic_price', 0): 34.375},
                               'B_location': {('location', 'resource_certain_availability', 0): 137.5,
                                              ('location', 'resource_deterministic_availability', 0): 343.75,
                                              ('location', 'resource_deterministic_price', 0): 304.6875},
                               'P_network': {('process_certain_capacity', 0): 137.5,
                                             ('process_deterministic_capacity', 0): 68.75,
                                             ('process_storage', 0): 50.0,
                                             ('process_storage_discharge', 0): 50.0},
                               'S_network': {('resource_deterministic_demand', 0): 0.0,
                                             ('resource_deterministic_revenue', 0): 137.5},
                               'R_network': {('resource_deterministic_demand', 0): 0.0,
                                             ('resource_deterministic_revenue', 0): 53125.0},
                               'C_network': {('resource_certain_availability', 0): 68.75,
                                             ('resource_deterministic_availability', 0): 68.75,
                                             ('resource_deterministic_price', 0): 34.375},
                               'B_network': {('resource_certain_availability', 0): 137.5,
                                             ('resource_deterministic_availability', 0): 343.75,
                                             ('resource_deterministic_price', 0): 304.6875},
                               'Fopex_process': {('location', 'process_certain_capacity', 0): 750.0,
                                                 ('location', 'process_deterministic_capacity', 0): 250.0,
                                                 ('location', 'process_storage', 0): 125.0,
                                                 ('location', 'process_storage_discharge', 0): 0.0},
                               'Vopex_process': {('location', 'process_certain_capacity', 0): 137.5,
                                                 ('location', 'process_deterministic_capacity', 0): 68.75,
                                                 ('location', 'process_storage', 0): 25.0,
                                                 ('location', 'process_storage_discharge', 0): 0.0},
                               'Capex_process': {('location', 'process_certain_capacity', 0): 7500.0,
                                                 ('location', 'process_deterministic_capacity', 0): 25000.0,
                                                 ('location', 'process_storage', 0): 2500.0,
                                                 ('location', 'process_storage_discharge', 0): 0.0},
                               'Incidental_process': {('location', 'process_certain_capacity', 0): 0.0,
                                                      ('location', 'process_deterministic_capacity', 0): 0.0,
                                                      ('location', 'process_storage', 0): 0.0,
                                                      ('location', 'process_storage_discharge', 0): 0.0},
                               'Fopex_location': {('location', 0): 1125.0},
                               'Vopex_location': {('location', 0): 231.25},
                               'Capex_location': {('location', 0): 35000.0},
                               'Incidental_location': {('location', 0): 0.0},
                               'Fopex_network': {0: 1125.0},
                               'Vopex_network': {0: 231.25},
                               'Capex_network': {0: 35000.0},
                               'Incidental_network': {0: 0.0},
                               'Inv_network': {('location',
                                                'process_storage_resource_deterministic_demand_stored',
                                                0): 50.0},
                               'Cost_network': {None: 37147.1875},
                               'Inv_cost': {('location',
                                             'process_storage_resource_deterministic_demand_stored',
                                             0): 5.0},
                               'Inv_cost_location': {('location', 0): 5.0},
                               'Inv_cost_network': {0: 5.0},
                               'objective': 15977.8125})
