"""Emission component, measured on the basis of impact potential 
"""

from dataclasses import dataclass, fields

from .._base._defined import _Simple
from ._commodity import _Commodity
from ...attrs.bounds import EmnBounds


@dataclass
class Emission(EmnBounds, _Simple, _Commodity):
    """Emission are generated by Commodity use, buy, sell
    and setting up and running Operation

    Attributes:
        emit (IsBoundInput): bound on amount emitted at some spatiotemporal disposition
        basis (str): basis of the component
        citation (dict): citation of the component
        block (str): block of the component
        introduce (str): index in scale when the component is introduced
        retire (str): index in scale when the component is retired
        label (str): label of the component
    """

    def __post_init__(self):
        _Simple.__post_init__(self)
        _Commodity.__post_init__(self)

    @staticmethod
    def inputs():
        """Input attributes"""
        return [f.name for f in fields(EmnBounds)]

    @property
    def emissions(self):
        """Emissions across the components"""
        return self.taskmaster.report_emissions
