"""The nature of attributes that feature in Components of the System model"""

nature = {
    'players': {
        'expenses': [],
        'quantify': ['owns', 'has', 'needs'],
        'landuse': [],
        'resourcebnds': [],
        'resourceexps': [],
        'materialuse': [],
        'emitted': [],
        'loss': [],
    },
    'emissions': {
        'expenses': [],
        'quantify': ['emit'],
        'landuse': [],
        'resourcebnds': [],
        'resourceexps': [],
        'materialuse': [],
        'emitted': [],
        'loss': [],
    },
    'cash': {
        'expenses': [],
        'quantify': ['spend', 'earn'],
        'landuse': [],
        'resourcebnds': [],
        'resourceexps': [],
        'materialuse': [],
        'emitted': [],
        'loss': [],
    },
    'land': {
        'expenses': ['cost'],
        'quantify': ['use'],
        'landuse': [],
        'resourcebnds': [],
        'resourceexps': [],
        'materialuse': [],
        'emitted': ['emission'],
        'loss': [],
    },
    'materials': {
        'expenses': ['cost'],
        'quantify': ['use'],
        'landuse': [],
        'resourcebnds': [],
        'resourceexps': [],
        'materialuse': [],
        'emitted': ['emission'],
        'loss': [],
    },
    'resources': {
        'expenses': ['buy_price', 'sell_price', 'credit', 'penalty'],
        'quantify': ['buy', 'sell', 'ship', 'deliver'],
        'landuse': [],
        'resourcebnds': [],
        'resourceexps': [],
        'materialuse': [],
        'emitted': ['emission'],
        'loss': [],
    },
    'processes': {
        'expenses': ['capex', 'opex'],
        'quantify': ['capacity', 'operate'],
        'landuse': ['land'],
        'resourcebnds': ['buy', 'sell'],
        'resourceexps': ['buy_price', 'sell_price', 'credit', 'penalty'],
        'materialuse': ['material'],
        'emitted': ['emission'],
        'loss': [],
    },
    'storages': {
        'expenses': ['capex', 'opex'],
        'quantify': ['capacity', 'operate'],
        'landuse': ['land'],
        'resourcebnds': [],
        'resourceexps': [],
        'materialuse': ['material'],
        'emitted': ['emission'],
        'loss': ['loss'],
    },
    'transits': {
        'expenses': ['capex', 'opex'],
        'quantify': ['capacity', 'operate'],
        'landuse': ['land'],
        'resourcebnds': ['ship', 'deliver'],
        'resourceexps': [],
        'materialuse': ['material'],
        'emitted': ['emission'],
        'loss': ['loss'],
    },
}
